/** Operator explanations describe current product behavior, not provider promises. */
export const FIELD_HELP = {
  avatarWakePhrase: 'Phrase that wakes this avatar while it is on the Mirror. Avatars may share a phrase. Save, check and publish changes; the active avatar uses its own phrase. Test pronunciation with the real microphone.',
  avatarSleepPhrase: 'Command visitors say to put this avatar to sleep. This is separate from the farewell it speaks. The next conversation uses the published phrase; quoted or negated mentions do not request sleep.',
  avatarName: 'The character’s display name, up to 80 characters. It is also included in the character instructions. Save, check and publish to use it in the next conversation.',
  personality: 'Describe who this character is, its attitude, knowledge and conversational boundaries. For example: “A patient museum guide who gives short answers.” Up to 12,000 characters; applies to the next conversation after publishing.',
  idle: 'Seconds of inactivity before the mirror goes to sleep. Both visitor and avatar speech keep it awake. Use a whole number from 1 to 86,400; for example, 300 means five minutes.',
  editingAvatar: 'Choose the character whose draft you want to edit. This does not switch the visitor’s Mirror. Save unfinished changes before switching; use “Use on Mirror” after publishing to activate a character.',
  modelBundle: 'The Live2D Cubism rig used to draw this character. Built-in Ren is bundled with the app; imported names come from the shared rig library. Selecting a rig changes this draft’s appearance. Save, check and publish before it reaches the Mirror.',
  wakeGreeting: 'The words the avatar is asked to say when a conversation starts. Write the complete greeting, up to 500 characters. This is spoken output; it does not change the phrase used to wake the mirror.',
  sleepFarewell: 'The exact farewell the avatar is asked to say before returning to sleep. Up to 500 characters. The mirror waits for the farewell’s audio to finish before showing its sleeping presentation.',
  visibility: 'Always visible keeps the avatar on screen while sleeping. Emerge from mist hides it behind the sleeping background and reveals it on wake. Entrance and exit times control the transition.',
  background: 'Choose an imported image or looping video for the sleeping background. Built-in atmosphere uses the default background. A background video is silent; choose Sleep ambience separately for its sound.',
  ambience: 'Choose music that loops while the mirror is asleep, or No ambience for silence. It fades out when the mirror wakes. Import audio through Media library if the track you want is missing.',
  ambienceVolume: 'This avatar’s sleeping ambience level: 0% is silent and 100% uses the track’s full level. The System BGM volume multiplies this setting, so a lower global BGM level also makes this ambience quieter.',
  entrance: 'How many seconds the avatar’s waking transition takes. Range: 0.2–10 seconds. Shorter feels quicker; longer makes the reveal more gradual. Preview entrance to see the draft locally.',
  exit: 'How many seconds the transition back to the sleeping presentation takes. Range: 0.2–10 seconds. It follows the farewell. Preview exit to see the draft locally.',
  baseVoice: 'The provider voice used to generate speech. Available choices come from the app’s approved voice list. Use Generate test voice to hear the choice; a local audio file cannot demonstrate a different provider voice. Published changes apply to the next conversation.',
  speechSpeed: 'Provider speech speed, from 0.5× to 1.5×. 1× is the normal pace; lower is slower and higher is faster. Generate a new test voice to hear the change. It does not change local-file playback speed.',
  deliveryStyle: 'Describe how to speak: pacing, warmth, energy, language or tone. For example: “Calm, curious, brief answers in Traditional Chinese.” Up to 2,000 characters. Generate a new audition to hear changes; style instructions are not an exact acoustic guarantee.',
  effectsEnabled: 'Turn the local voice-processing effects on or off. Off plays the original generated or recorded voice; the System Avatar audio volume still applies. Use Original / Processed to compare the same sample.',
  pitch: 'Raises or lowers the voice’s musical pitch, from −12 to +12 semitones. 0 leaves pitch unchanged; 12 semitones is one octave. Try small changes first, then compare Original and Processed.',
  formant: 'Changes the voice’s apparent body or vocal-tract resonance, from −6 to +6 semitones. Lower values tend to sound larger or darker; higher values smaller or lighter. This is separate from musical pitch.',
  warmth: 'Boosts or reduces low-frequency tone, from −6 to +6 dB. Positive values add warmth and weight; negative values make the voice leaner. 0 leaves this tone control neutral.',
  brightness: 'Boosts or reduces high-frequency tone, from −6 to +6 dB. Positive values add clarity and edge; negative values soften the voice. Too much can make sibilant sounds harsh.',
  grit: 'Adds a rough, saturated texture to the voice. 0 is clean; higher values add more grit, up to 0.30. Start with a small amount and listen to a complete sentence.',
  roomMix: 'How much short room reverberation is mixed into the voice, from 0 to 0.25. 0 is dry; 0.25 is the maximum 25% room mix. More room can make words less distinct.',
  outputTrim: 'Attenuates the processed voice after effects, from −18 to 0 dB. 0 adds no attenuation; negative values make it quieter. Use this to balance an avatar’s effect preset; System Avatar audio controls overall playback volume.',
  formantCompensation: 'Preserves vocal resonance when pitch changes, helping avoid a strongly tiny or oversized voice. Body / formant remains a separate creative control. Compare on and off using the same sample.',
  roomSize: 'Short uses a 120 ms room response; Medium uses 250 ms for a longer sense of space. Room mix controls how much is audible. A larger room also leaves a longer audio tail.',
  localSpeech: 'Choose an authorized local speech sample for an offline effects audition. Maximum: 20 MB and 30 seconds of decoded audio. It stays local and does not use the microphone or generate provider speech.',
  loopFixture: 'Repeat the selected local sample until you press Stop or leave the preview. Useful for comparing effects. This does not loop a generated provider audition.',
  libraryModel: 'Choose a rig from the shared Live2D library for silent local inspection. Loading it does not publish or switch the visitor’s avatar. Assign it in Appearance when you want a character to use it.',
  libraryName: 'A readable name for this imported rig, up to 60 characters. Saving the library label changes how it is listed across the Console; it does not rename its files or publish an avatar.',
  libraryVersion: 'An optional version label, up to 16 characters; for example, v10. Use letters, digits, dots, hyphens, underscores or plus signs. Save library label to update the shared list. This does not modify the model’s files.',
  sceneName: 'A name for this scene in the Console, from 1 to 120 characters. A scene contains ordered steps; actions inside each step start together. Save, check and publish for live use. This name is not a spoken trigger phrase.',
  sceneEnabled: 'Allow this scene to run when tested or triggered. Turn off to keep the scene in the draft without allowing it to start. Its trigger phrases also need to be enabled.',
  triggerPhrase: 'Use a fixed prefix plus a short name, for example 施放咒語，下雨. Say it in one utterance without extra words. The fixed prefix accepts 咒語 or 咒语; punctuation and Chinese spacing are normalized. The complete command must match. Give each spell a distinct name; save, check and publish before live use. Existing complete phrases remain supported (1–240 characters).',
  triggerEnabled: 'Allow this phrase to start its scene. Turn off to keep the phrase without triggering. The linked scene must also be enabled.',
  cooldown: 'Minimum seconds before this phrase can trigger again, from 0 to 86,400 (24 hours). 0 removes the cooldown; 5 means wait five seconds. Save, check and publish for live use. This limits repeated triggers, not how long the scene plays.',
  stepName: 'A name for this step, from 1 to 120 characters. Steps run from top to bottom, and all enabled actions assigned to this step start together. Save the scene to retain changes.',
  endsWhen: 'After a duration advances when the timer ends. When video finishes waits for a selected once-playing video in this step. Until stopped holds the final step until stopped or its maximum time is reached; it cannot be used in the middle of a scene.',
  stepDuration: 'Seconds before this step ends and the next starts. This control accepts 0.1–600 seconds (10 minutes). It controls the step, not the length of an individual audio or video file. Save the scene to retain changes.',
  maximumTime: 'Maximum seconds an Until stopped final step may remain active: 1–86,400 seconds (24 hours). Stop ends it earlier. Save the scene to retain this time limit.',
  completionVideo: 'Select the video action whose completion ends this step. Only video actions assigned to this step with Playback set to Once are eligible. Looping videos cannot signal this end condition.',
  assignedAction: 'Include this existing action in the selected step. Checked actions start together when the step begins. Unchecking removes the assignment only; the reusable action stays in the library.',
  actionName: 'A readable name for this reusable action, from 1 to 120 characters. It may be assigned to multiple steps or avatars, so check its usage before saving. Renaming does not change a spoken trigger.',
  actionEnabled: 'Allow this action to execute when an assigned step runs. Turn off to keep its settings and assignments without executing it.',
  actionKind: 'Dialogue speaks text; Avatar motion plays a Cubism motion; Expression applies a facial pose; Lighting and Fog use approved hardware presets; Music plays, fades or stops audio; Image / video shows a visual. Changing kind replaces the kind-specific settings.',
  dialogue: 'The complete words to request verbatim when this action runs, from 1 to 1000 characters. Keep them short enough for the step. System Avatar audio controls the speech volume. Save, check and publish for live scene use.',
  motionGroup: 'Choose a motion group exported by the rig. The scene requests that group’s first clip. A name does not guarantee every rig has the matching animation; test it with the assigned avatar.',
  expression: 'Choose an exported Cubism expression pose. It changes the face until another expression or reset replaces it. Availability and visible artwork depend on the assigned rig; test the result.',
  hardwareCommand: 'ON activates the approved preset; OFF releases it; Value requests a normalized level from 0 to 1. The configured adapter determines whether this is simulated or sent to supported hardware.',
  approvedPreset: 'The identifier of an already approved lighting or fog preset. It is not a free-form hardware command. Use a preset configured for your adapter; an unknown preset cannot control a device.',
  hardwareValue: 'A normalized preset level from 0 to 1. The hardware adapter defines what the level means; it is not universally brightness, power or fog density. Start with an approved low-output test.',
  musicCommand: 'Play starts the selected audio track. Fade changes the current track’s level over a duration. Stop ends the current track, optionally fading out first. These actions share the existing scene-music player.',
  musicAsset: 'Choose an imported audio asset for this action. Use Browse & upload audio if the track is missing. The scene-music path is controlled by the System BGM slider.',
  musicGain: 'This music action’s level from 0 to 1: 0 is silent, 0.5 is half amplitude, and 1 adds no attenuation. System BGM volume and speech ducking also apply.',
  musicLoop: 'Repeat this audio track until a Stop action, scene cleanup or sleep stops it. With Loop off, the file plays once. Looping audio does not by itself decide when the step ends.',
  fadeOut: 'Milliseconds used to fade the current music to silence before stopping, from 0 to 60,000. 0 stops immediately; 1000 means one second. Save, check and publish for live scene use.',
  targetGain: 'The music level at the end of the fade, from 0 to 1. 0 fades to silence and 1 restores the track’s full authored level. System BGM volume and speech ducking still apply.',
  fadeDuration: 'Milliseconds for the music level to move to Target gain, from 1 to 60,000. 1000 ms equals one second. Longer durations make a more gradual change. Save, check and publish for live scene use.',
  visualAsset: 'Choose an imported image or video to display in this step. Selecting a different asset resets playback and audio settings to safe defaults. Images are still; videos can play once or loop.',
  fit: 'Contain shows the whole image or video and may leave empty edges. Cover fills the display but crops edges when the aspect ratios differ. Preview on the portrait display to check important content.',
  playback: 'Once plays the video to its end and can be used with When video finishes. Loop repeats until the scene stops or replaces it. A looping video cannot serve as the completion video.',
  videoAudio: 'Muted silences the video’s embedded track. Embedded track plays audio from the video, if it has one, through System Sound effects volume and speech ducking. This does not add an audio track to a silent video.',
  videoGain: 'The embedded video track’s level, from 0 to 1. 0 is silent; 1 adds no attenuation. System Sound effects volume and speech ducking also apply.',
  videoFadeIn: 'Milliseconds for a video to fade from transparent to full opacity, from 0 to 10,000. Embedded audio follows the same ramp. 0 starts immediately.',
  videoFadeOut: 'Milliseconds for a video to fade to transparent at Stop or the natural end, from 0 to 10,000. Embedded audio follows the same ramp. 0 stops immediately.',
  resourceLock: 'Shared resources can be reused by other avatars. Check to restrict this resource to the avatar being edited. A lock owned by another avatar cannot be changed here. Save the draft to retain the scope change.',
  bgmVolume: 'Overall music and sleep-ambience volume for every avatar, including music-library previews. 0% mutes and 100% adds no attenuation. Applies immediately and saves automatically; authored track levels and speech ducking still apply.',
  avatarVolume: 'Overall conversation, recorded-speech and Voice Studio audition volume for every avatar. 0% mutes and 100% adds no attenuation. Applies immediately and saves automatically; voice-effect trim still applies.',
  effectsVolume: 'Overall embedded scene-video audio volume for every avatar. 0% mutes and 100% adds no attenuation. Applies immediately and saves automatically. Standalone audio assets currently use BGM, not this control.',
  microphone: 'Choose the input device for conversation and wake detection. Windows default follows the system choice when acquired. Changes take effect at the next conversation and wake-listener start; Start Conversation then Disconnect updates both.',
  speakers: 'Choose where voice, music, ambience and video audio play. Windows default follows the system output. Applies to attached playback paths immediately and saves automatically; an unavailable device produces a visible fallback reason.',
  eventModule: 'Filter diagnostic events by the subsystem that emitted them. All shows every subsystem. This changes the event list only; it does not enable or disable a module.',
  eventStatus: 'Filter by event result: success completed, info is informational, degraded indicates reduced capability or a fallback, and failed indicates an unsuccessful operation. All shows every result.',
  eventSource: 'Runtime shows events from the running app; mock shows simulated checks. All combines both. A successful mock event is not evidence that physical hardware worked.',
  phase: 'Choose the project phase whose stored demo evidence is shown. This selector only filters records; it does not start, accept or promote a phase.',
  configPersona: 'Legacy top-level persona name in the saved configuration. Prefer Avatars → Persona for character editing. Advanced config edits require Save Draft, Test Draft and publication before they affect the active configuration.',
  configVoice: 'Legacy top-level provider voice identifier. Prefer the approved Base voice dropdown in Avatars → Voice. Enter an exact supported ID; changing a name here does not create a new voice.',
  wakePhrase: 'The active avatar’s wake phrase. Edit each avatar in Avatars → Persona. Supported Mandarin and English phrases are compiled locally when checked and published; test actual pronunciation with the microphone.',
  avatarWakeTuning: 'Optional per-avatar sherpa detector parameters. Enable, save, check and publish to activate them in the next Dormant wake-listener run. Threshold, score and trailing blanks change detector sensitivity; they are parameter overrides, not neural fine-tuning, and do not carry accuracy evidence.',
  avatarWakeTuningEnable: 'When enabled, this avatar’s exact wake phrase uses the entered detector overrides. Disable to restore the verified package defaults.',
  avatarWakeThreshold: 'Optional detector threshold override from 0 to 1. Lower values may catch more speech but can increase false wakes. Blank uses the installed package default.',
  avatarWakeScore: 'Optional keyword score override above 0. Higher values can make a match easier but may increase false wakes. Blank uses the installed package default.',
  avatarWakeTrailingBlanks: 'Optional sherpa trailing-blank count from 1 to 100. Blank uses the installed package default. This changes detector timing, not the neural model.',
  wakeVersion: 'The installed wake model’s version identifier. Use the exact value from its approved package; arbitrary text does not download or replace a model.',
  wakePackage: 'The identifier of the installed, validated wake model package. It must agree with the model version. Custom avatar phrases use its token vocabulary; changing a phrase does not require replacing this package.',
  faceDetector: 'The configured face-detection model identifier. Detection locates faces; it does not confirm identity. Editing the ID does not install a model or start a deferred identity phase.',
  faceRecognizer: 'The configured face-recognition model identifier. Recognition can propose a candidate; private memory still requires verbal confirmation. Editing this ID does not install a model or authorize enrollment.',
  offlineVideo: 'Configured path to the local offline-loop video. Use an available, decodable asset. This is a fallback presentation asset, not the per-avatar sleeping background selected in Appearance.',
  avatarDirectory: 'Configured directory for avatar assets. Enter the expected existing local path. This field does not import a Cubism bundle; use Appearance or the rig library for managed model imports.',
  musicDirectory: 'Configured directory for local music assets. Enter the expected existing path. This field does not upload tracks; use Media library for managed audio imports.',
  lightingAdapter: 'Mock simulates lighting actions for checks. Physical requests the configured hardware adapter and approved presets; it does not automatically connect new hardware. A mock pass is not a physical-lighting test.',
  fogAdapter: 'Mock simulates fog actions. Physical requests the configured fog adapter and approved presets; it does not automatically connect a machine. Use only approved hardware presets.',
  musicAdapter: 'Mock simulates music actions for checks. Physical selects the configured playback adapter for actual output. Validate the draft and test the selected speakers before relying on a scene.',
  dialogueModel: 'Model ID for the simulated realtime conversation role. Save Model Draft stages the change for testing and publication in Advanced config. Create next mock session/job updates the simulated loaded value. Live conversation still uses versioned runtime configuration.',
  transcriptionModel: 'Model ID for the simulated input-transcription role. Save Model Draft stages the change for testing and publication in Advanced config. Create next mock session/job updates the simulated loaded value. This does not change live transcription or download a model.',
  extractionModel: 'Model ID for the simulated memory-extraction role. Save Model Draft stages the change for testing and publication in Advanced config. Create next mock session/job updates the simulated loaded value. This does not enable memory storage or change the versioned runtime model.',
} as const

export const VOICE_FIELD_HELP = {
  pitchSemitones: FIELD_HELP.pitch, formantSemitones: FIELD_HELP.formant, warmthDb: FIELD_HELP.warmth,
  brightnessDb: FIELD_HELP.brightness, grit: FIELD_HELP.grit, roomMix: FIELD_HELP.roomMix, outputTrimDb: FIELD_HELP.outputTrim,
} as const

export function cubismParameterHelp(id: string, name: string, min: number, max: number, defaultValue: number): string {
  return `${name} (${id}) is a local rig parameter. Range: ${min} to ${max}; neutral/default: ${defaultValue}. Drag to preview, or use Min / Default / Max. Stop / reset clears manual values. Direction and visible movement depend on this rig’s artwork; this does not edit the model file or publish the avatar.`
}
